sudo: required
services:
  - docker

before_install:
  - docker build -t akshat105/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akshat105/react-test yarn test

after_success:
  - docker build -t akshat105/multi-client ./client
  - docker build -t akshat105/multi-worker ./worker
  - docker build -t akshat105/multi-server ./server
  - docker build -t akshat105/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push akshat105/multi-client
  - docker push akshat105/multi-worker
  - docker push akshat105/multi-server
  - docker push akshat105/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-449467373802
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
